:driver: :poltergeist
:dimensions:
  - 1024

:capture_dir: "./public/captures"
:baseline_dir: "./public/baselines"
:thumbnail_dir: "./public/thumbnails"

:base_url: "http://lance.com"

:thumbnail: true
:compare_type: Highlight
:map:
  - "/"
  - "/aboutus"
  - "/littleleague"